image: iclink/onnc_dev:1.1

variables:
    GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - build_ninja

before_script:
  - git clean -ffdx
  - git submodule foreach git clean -ffdx

build:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make -j$(nproc)
    - ctest -j$(nproc)

build_ninja:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake .. -G Ninja
    - ninja
    - ctest -j$(nproc)
