image: iclink/onnc_dev:1.1

variables:
    GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - build_ninja

before_script:
  - git clean -ffdx
  - git submodule foreach git clean -ffdx

build:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make -j$(nproc)
    - ctest -j$(nproc)

build_separate:
  stage: build
  script:
    - mkdir build_external
    - pushd build_external
    -   cmake ../external
    -   make -j$(nproc)
    - popd
    - mkdir build_src
    - pushd build_src
    -   cmake ../src
          -DONNX_INSTALL_DIR=$PWD/../build_external/Install/onnx
          -DSKYPAT_INSTALL_DIR=$PWD/../build_external/Install/skypat
          -DBMTAP_INSTALL_DIR=$PWD/../build_external/Install/bmtap2
          -DBMTAP_SOURCE_DIR=$PWD/../external/bmtap2
          -DBMTAP_BINARY_DIR=$PWD/../build_external/Build/bmtap2
    -   make -j$(nproc)
    -   ctest -j$(nproc)
    - popd

build_ninja:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake .. -G Ninja
    - ninja
    - ctest -j$(nproc)
