image: iclink/onnc_dev:1.1

variables:
    GIT_SUBMODULE_STRATEGY: recursive
    GIT_STRATEGY: clone

stages:
  - build
  - build_ninja

build:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make -j$(nproc)
    - make test

build_ninja:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake .. -G Ninja
    - ninja
    - ninja test
