language: c
sudo: required

branches:
  only:
  - master

matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx

services:
  - docker

stages:
  - name: deploy
    # require the branch name to be master (note for PRs this is the base branch name)
    if: branch = master

stages:
  - name:  osx-test
     if: os = osx
  
  - name: ubuntu-test  
     if: os = linux
     jobs:
      include:
        - stage: test  
          before_install:
            - sudo apt-get update
            - sudo apt-get upgrade lxc-docker
            #- echo 'DOCKER_OPTS="-H tcp://127.0.0.1:2375 -H unix:///var/run/docker.sock -s devicemapper"' | sudo tee /etc/default/docker > /dev/null
            - sudo service docker restart
            - sleep 5
            - sudo docker pull ubuntu:trusty
            - sudo docker create --privileged=true -t --name ubuntu  ubuntu:trusty
            - sudo docker start ubuntu
            - sudo docker exec -t ubuntu /bin/bash -c "apt-get update"
            - sudo docker exec -t ubuntu /bin/bash -c "rm -rf /var/lib/apt/lists/*"
            - sudo docker exec -t ubuntu /bin/bash -c "pip install future numpy protobuf lit"
            - sudo docker exec -t ubuntu /bin/bash -c "pip3 install jinja2"
            - sudo docker exec -t ubuntu /bin/bash -c "git clone https://github.com/ONNC/umbrella.git"
            - sudo docker exec -t ubuntu /bin/bash -c "git submodule init"
            - sudo docker exec -t ubuntu /bin/bash -c "git submodule update"
            - sudo docker exec -t ubuntu /bin/bash -c "mkdir ./umbrella/onnc-build"
            - sudo docker exec -t ubuntu /bin/bash -c "./umbrella/build.sh dbg ./umbrella/onnc-build"
          #script:
          # Run tests in Container
          # - sudo docker exec -t  "docker-you-wanted" /bin/bash -c "command-you-wanted"

notifications:
  email: false


