branches: 
  only: 
    - travis
language: c

os:
  - linux
#  - osx


sudo: required
notifications: 
  email: false

git:
    submodules: false

services: 
  - docker

before_install: 
  - sudo apt-get update
  - sudo service docker restart
  - sleep 5
  - sudo docker pull ubuntu:trusty

matrix:
  include:
    - os: osx
      script:

    - os: linux
      script: 
          - sudo docker create --privileged=true -t --name ubuntu  centos:centos7
          - sudo docker start container

    - os: linux
      script: 
          - sudo docker create --privileged=true -t --name ubuntu  fedora:27
          - sudo docker start container

  
    - os: linux
      script: 
          - sudo docker create --privileged=true -t --name container  ubuntu:trusty
          - sudo docker start container
          - sudo docker exec -t container /bin/bash -c "apt-get update"
          - sudo docker exec -t container /bin/bash -c "apt-get install -y --no-install-recommends curl"
          - sudo docker exec -t container /bin/bash -c "apt-get install -y --no-install-recommends sudo"
          - sudo docker exec -t container /bin/bash -c "apt-get install -y --no-install-recommends build-essential"
          - sudo docker exec -t container /bin/bash -c "apt-get install -y --no-install-recommends gcc-arm-none-eabi"
          - sudo docker exec -t container /bin/bash -c "apt-get install -y --no-install-recommends libnewlib-arm-none-eabi"
          - sudo docker exec -t container /bin/bash -c "apt-get install -y --no-install-recommends libboost-all-dev"
          - sudo docker exec -t container /bin/bash -c "apt-get install -y --no-install-recommends pkg-config"
          - sudo docker exec -t container /bin/bash -c "apt-get install -y --no-install-recommends python3"
          - sudo docker exec -t container /bin/bash -c "apt-get install -y --no-install-recommends python3-pip"
          - sudo docker exec -t container /bin/bash -c "apt-get install -y --no-install-recommends python3-setuptools"
          - sudo docker exec -t container /bin/bash -c "apt-get install -y --no-install-recommends libgoogle-glog-dev"
          - sudo docker exec -t container /bin/bash -c "apt-get install -y --no-install-recommends libgtest-dev"
          - sudo docker exec -t container /bin/bash -c "apt-get install -y --no-install-recommends libiomp-dev"
          - sudo docker exec -t container /bin/bash -c "apt-get install -y --no-install-recommends libleveldb-dev"
          - sudo docker exec -t container /bin/bash -c "apt-get install -y --no-install-recommends liblmdb-dev"
          - sudo docker exec -t container /bin/bash -c "apt-get install -y --no-install-recommends libopencv-dev"
          - sudo docker exec -t container /bin/bash -c "apt-get install -y --no-install-recommends libopenmpi-dev"
          - sudo docker exec -t container /bin/bash -c "apt-get install -y --no-install-recommends libsnappy-dev"
          - sudo docker exec -t container /bin/bash -c "apt-get install -y --no-install-recommends libprotobuf-dev"
          - sudo docker exec -t container /bin/bash -c "apt-get install -y --no-install-recommends openmpi-bin"
          - sudo docker exec -t container /bin/bash -c "apt-get install -y --no-install-recommends openmpi-doc"
          - sudo docker exec -t container /bin/bash -c "apt-get install -y --no-install-recommends libgflags-dev"
          - sudo docker exec -t container /bin/bash -c "apt-get install -y --no-install-recommends automake"
          - sudo docker exec -t container /bin/bash -c "apt-get install -y --no-install-recommends libtool"
          - sudo docker exec -t container /bin/bash -c "apt-get install -y --no-install-recommends xz-utils"
          - sudo docker exec -t container /bin/bash -c "apt-get install -y --no-install-recommends make"
          #- sudo docker exec -t container /bin/bash -c "apt-get install -y --no-install-recommends cmake"

          - sudo docker exec -t container /bin/bash -c "curl https://cmake.org/files/v3.12/cmake-3.12.0.tar.gz --output cmake-3.12.0.tar.gz"
          - sudo docker exec -t container /bin/bash -c "tar xvf cmake-3.12.0.tar.gz"
          - sudo docker exec -t container /bin/bash -c "cd cmake-3.12.0 && ./bootstrap && make -j8 && make install"
          - sudo docker exec -t container /bin/bash -c "apt-get install -y --no-install-recommends g++"
          - sudo docker exec -t container /bin/bash -c "apt-get install -y --no-install-recommends python"
          - sudo docker exec -t container /bin/bash -c "apt-get install -y --no-install-recommends git"
          - sudo docker exec -t container /bin/bash -c "apt-get install -y --no-install-recommends protobuf-compiler"
          - sudo docker exec -t container /bin/bash -c "apt-get install -y --no-install-recommends libprotoc-dev"
          - sudo docker exec -t container /bin/bash -c "apt-get install -y --no-install-recommends python-pip"
          - sudo docker exec -t container /bin/bash -c "apt-get install -y --no-install-recommends python-dev"
          - sudo docker exec -t container /bin/bash -c "apt-get install -y --no-install-recommends python-setuptools"
          - sudo docker exec -t container /bin/bash -c "apt-get install -y --no-install-recommends bison"
          - sudo docker exec -t container /bin/bash -c "apt-get install -y --no-install-recommends flex"
          - sudo docker exec -t container /bin/bash -c "apt-get install -y --no-install-recommends ninja-build"
          - sudo docker exec -t container /bin/bash -c "apt-get install -y --no-install-recommends cmake-curses-gui"
          #- sudo docker exec -t container /bin/bash -c "apt-get install -y --no-install-recommends llvm-5.0-tools"
          #- sudo docker exec -t container /bin/bash -c "apt-get install -y --no-install-recommends clang-5.0"
          #- sudo docker exec -t container /bin/bash -c "apt-get install -y --no-install-recommends clang-tidy-5.0"
          #- sudo docker exec -t container /bin/bash -c "apt-get install -y --no-install-recommends clang-format-5.0"
          #- sudo docker exec -t container /bin/bash -c "curl http://releases.llvm.org/6.0.1/llvm-5.0.2.src.tar.xz"
          #- sudo docker exec -t container /bin/bash -c "tar xvf llvm-5.0.2.src.tar.xz"
          #- sudo docker exec -t container /bin/bash -c "cd llvm-5.0.2.src && mkdir build && cd build && cmake ../"
          #- sudo docker exec -t container /bin/bash -c "cd llvm-5.0.2.src && cd build && make -j4"
          - sudo docker exec -t container /bin/bash -c "apt-get install -y --no-install-recommends gcovr"
          - sudo docker exec -t container /bin/bash -c "rm -rf /var/lib/apt/lists/*"
          - sudo docker exec -t container /bin/bash -c "pip install future numpy protobuf lit"
          - sudo docker exec -t container /bin/bash -c "pip3 install jinja2"
          - sudo docker exec -t container /bin/bash -c "git clone https://github.com/ONNC/umbrella.git"
          - sudo docker exec -t container /bin/bash -c "cd umbrella && git submodule init"
          - sudo docker exec -t container /bin/bash -c "cd umbrella && git submodule update"
          - sudo docker exec -t container /bin/bash -c "mkdir ./umbrella/onnc-build"
          #- sudo docker exec -t container /bin/bash -c "./umbrella/build.sh dbg ./umbrella/onnc-build"
          - sudo docker exec -t container /bin/bash -c "cd umbrella && ./build.cmake.sh dbg ./onnc-build"

       