branches: 
  only: 
    - travis
language: c
sudo: required
notifications: 
  email: false

# Handle git submodules yourself

git:
    submodules: false

services: 
  - docker

before_install: 
  - sudo apt-get update
  - sudo service docker restart
  - sleep 5
  - sudo docker pull ubuntu:trusty

script: 
  - sudo docker create --privileged=true -t --name ubuntu  ubuntu:trusty
  - sudo docker start ubuntu
  - sudo docker exec -t ubuntu /bin/bash -c "apt-get update"
  - sudo docker exec -t ubuntu /bin/bash -c "apt-get install -y --no-install-recommends curl"
  - sudo docker exec -t ubuntu /bin/bash -c "rm -rf /var/lib/apt/lists/*"
  - sudo docker exec -t ubuntu /bin/bash -c "pip install future numpy protobuf lit"
  - sudo docker exec -t ubuntu /bin/bash -c "pip3 install jinja2"
  - sudo docker exec -t ubuntu /bin/bash -c "git clone https://github.com/ONNC/umbrella.git"
  - sudo docker exec -t ubuntu /bin/bash -c "git submodule init"
  - sudo docker exec -t ubuntu /bin/bash -c "git submodule update"
  - sudo docker exec -t ubuntu /bin/bash -c "mkdir ./umbrella/onnc-build"
  - sudo docker exec -t ubuntu /bin/bash -c "./umbrella/build.sh dbg ./umbrella/onnc-build"
   

